language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 2bg0xgyjVhPxQlr2bOhqDDpwhxpGLYJ8OoEa+4UVS/WE3TwsaTzmejI6/wfswFnUGCUHqaOBSFqQK/2jwwzxxITYWuiWBOaUKlb6GcFI3X2Ep3YPUDoZyOJ5PKGObj1RCd3fHK2iGPNtBlBzHwTnvQP0fm1KuP6RvQ4pqT6T38nebBo7tBiWYhxuTDmlQ+WONWvx8CYy1RsQoWhRNTPc1smdPylVwFFeGIhj953kk9giscPNjWtc9gLGL/FfFQ25iDhbkHQx2Bf6gZalx36AsKkDkn6rXudpDB+TxQ4dlQYmHFxX2tlIhChNa+VBWt6aRezo7gReGCAdpbrp2fXxaJOjFSDggmcbA6Lecflrpxga+SOKt5crTQ4Yfgb2FCutiF5Y6W8A8hQfvz7loR30OhefggtY5o8iQQqgnddubP+LjNPHlv8FBV0HeL5hMBGzQOlcqnHaw53zQQYruEENGzvA5gV6/4ZvNOubeeUbjxTq4fql0CeGOgQU4A7cV56YKLOYHmqLwPir0jdObBm4Wg5dxD6cGrRrVAbKsVrCsx/WgX8zTPCLIIxU6UYQ0bn9dAM4uf0SOwjDXzusIeElkTe1q3Yo27no4inW8FGFY5gB7eesGBLnMo8A1sEH4Gvi1LLJDjv6sLH93vmcakM1pJt/NB3i4ejdqp1RHp45AM0=
  app: me-lance
  on:
    repo: HypeUFO/me-lance
